const ACTION_TYPES = {
  START_LOADING: 'START_LOADING',
  FINISH_LOADING: 'FINISH_LOADING',
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  DELETE_NOTIFICATION: 'DELETE_NOTIFICATION',
}

export default ACTION_TYPES;